### ISSUE TITLE
DepthCam script can not find

### ISSUE THREAD

**Issue by yangjob** [mbaske/ml-drone-collection#2]
![图片](https://user-images.githubusercontent.com/33831043/77241404-95742880-6c2c-11ea-9c15-fbd61376fb00.png)
![图片](https://user-images.githubusercontent.com/33831043/77241371-28609300-6c2c-11ea-8215-34d72bb1e964.png)
![图片](https://user-images.githubusercontent.com/33831043/77241429-e2f09580-6c2c-11ea-9e6b-c70206578701.png)

**Comment by Shivamc489** [comment]
It is resolved now, 
I contacted him on youtube comments and owner corrected it.
